language: node_js

os:
  - linux
  - osx

before_script: npm run lint
after_success:
  - npm run coverage
  - npm run coveralls

node_js:
  - "6"
  - "7"
  - "8"
  - "9"

cache:
  directories:
    - "node_modules"
