language: node_js

os:
  - linux
  - osx

before_script: npm run lint
after_success: npm run coverage-coveralls

node_js:
  - "6"
  - "7"
  - "8"
  - "node"

cache:
  directories:
    - "node_modules"